### ISSUE TITLE
ERRor 

### ISSUE THREAD

**Issue by Aliraheem** [ttslr/python-MCD#3]
can you please help me to fix this error?

Processing -----------6.wav
mgc of GT/6.wav is ok!
theq() : determinant of the normal matrix is too small!
mgcep : Error in theq() at 0th iteration!
theq() : determinant of the normal matrix is too small!
mgcep : Error in theq() at 1th iteration!
Traceback (most recent call last):
  File "MCD-DTW.py", line 55, in <module>
    mgc2 = readmgc(filename2)
  File "MCD-DTW.py", line 29, in readmgc
    mgc = pysptk.mgcep(frames, order, alpha, gamma)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-11>", line 2, in mgcep
  File "/home/ali/.local/lib/python3.6/site-packages/pysptk/util.py", line 66, in apply_along_last_axis
    ret = np.apply_along_axis(func, -1, *args, **kwargs)
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "/home/ali/.local/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 402, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-10>", line 2, in mgcep
  File "/home/ali/.local/lib/python3.6/site-packages/pysptk/util.py", line 89, in automatic_type_conversion
    return func(*args, **kwargs).astype(dtypein)
  File "/home/ali/.local/lib/python3.6/site-packages/pysptk/sptk.py", line 760, in mgcep
    otype,
  File "pysptk/_sptk.pyx", line 211, in pysptk._sptk.mgcep
RuntimeError: failed to compute mgcep; error occured in theq

**Comment by wfengyu** [comment]
I have encountered the same problem, is you solved?

**Comment by Aliraheem** [comment]
I found another library (method) to calculate the MCD values. Please search for another one!

**Comment by wfengyu** [comment]
> I found another library (method) to calculate the MCD values. Please search for another one!

If it is convenient for you, can you share the link with me? Thank you very much

**Comment by Aliraheem** [comment]
I used this https://github.com/jasminsternkopf/mel_cepstral_distance.
it worked with me
